name: CI

on: [push, pull_request]


jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache PyPI
      uses: actions/cache@v2.1.6
      with:
        key: pip-${{ hashFiles('**/requirements.txt') }}
        path: ~/.cache/pip
        restore-keys: pip-
    - name: Install dependencies
      uses: py-actions/py-dependency-install@v2.1.0
    - name: Run tests
      run: python test_runner.py
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Flake8
      run: python -m pip install flake8
    - name: Run lint
      # TODO  Fix unlinted files
      run: python -m flake8 --exclude=solver.py,render.py,belt_balancer.py,make_block.py,tilemaps.py,optimisations.py .
      