name: CI

on: [push, pull_request]


jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        python-version: ['3.8', '3.10']
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: pip install -e .
    - name: Run tests
      run: python -m unittest
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Flake8
      run: python -m pip install flake8
    - name: Run lint
      # TODO  Fix unlinted files
      run: python -m flake8 --exclude=render.py,tilemaps.py factorio_sat test
      